version: '2.2'
services:
  db:
    image: postgres:11.2-alpine
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 1s
      retries: 30

  web:
    restart: always
    user: calculator_user
    build: .
    command: ./start.sh
    volumes:
      - ./src:/calculator_code
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
