# Generated by Django 3.1.2 on 2020-10-18 22:32
import logging

from django.db import migrations

DEFAULT_STATES = [
    ('Utah', 'UT'),
    ('Nevada', 'NV'),
    ('Texas', 'TX'),
    ('Alabama', 'AL'),
    ('California', 'CA')
]

DEFAULT_STATE_TAXES = [
    ('UT', 6.85),
    ('NV', 8),
    ('TX', 6.25),
    ('AL', 4),
    ('CA', 8.25)
]

DEFAULT_ORDER_DISCOUNTS = [
    (1000, 3),
    (5000, 5),
    (7000, 7),
    (10000, 10),
    (50000, 15)
]


def add_default_states(apps, schema_editor):
    State = apps.get_model('api', 'State')

    for name, code in DEFAULT_STATES:
        State.objects.get_or_create(name=name, code=code)


def add_default_state_taxes(apps, schema_editor):
    State = apps.get_model('api', 'State')
    StateTax = apps.get_model('api', 'StateTax')

    logging.error([state.code for state in State.objects.all()])
    for state_code, state_tax_rate in DEFAULT_STATE_TAXES:
        logging.error(f'{state_code=}')
        state = State.objects.get(code=state_code)
        StateTax.objects.get_or_create(state=state, tax_rate=state_tax_rate)


def add_default_discounts(apps, schema_editor):
    Discount = apps.get_model('api', 'Discount')

    for order_price, discount_rate in DEFAULT_ORDER_DISCOUNTS:
        Discount.objects.get_or_create(order_price=order_price, discount_rate=discount_rate)


# def populate_all_tables(apps, schema_editor):
#     add_default_states(apps, schema_editor)
#     add_default_state_taxes(apps, schema_editor)
#     add_default_discounts(apps, schema_editor)


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_default_states),
        migrations.RunPython(add_default_state_taxes),
        migrations.RunPython(add_default_discounts),
    ]
